fastlane_version "1.57.0"

default_platform :ios

platform :ios do
  desc "Builds certificates"
  lane :cert do
    cert(development: true, output_path: 'fastlane/certificates/')
    sigh(development: true, output_path: 'fastlane/certificates/', adhoc: true)
    pem(development: true, output_path: 'fastlane/certificates/')
    cert(output_path: 'fastlane/certificates/')
    sigh(output_path: 'fastlane/certificates/')
    pem(output_path: 'fastlane/certificates/')
  end
end